#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'user_styles'

client = UserStyles.new({ :username => 'user', :password => 'password' })

Dir.glob('*.css').each do |file|
  basename = File.basename(file, '.css')
  name     = "GitHub Style for paperboy-#{basename}"
  style    = client.get_style(name)

  css = File.read(file)

  if style
    client.update_style({
      :url         => style[:edit],
      :name        => name,
      :description => name,
      :css         => css
    })
  else
    css = %!@-moz-document url-prefix("https://github.com/organizations/paperboy-#{basename}"), url-prefix("https://github.com/paperboy-#{basename}") {! + css + "}"
    client.add_style({
      :name        => name,
      :description => name,
      :css         => css
    })
  end
end

